name: Receive PR
run-name: "${{ github.event.pull_request.title }}: generate artifact (${{ github.event.pull_request.head.sha }})"
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version-file: "./.nvmrc"
          cache: "yarn"
          cache-dependency-path: "./yarn.lock"   
      - if: steps.setup-node.outputs.src == 'true'
        name: Install Dependencies
        id: install
        run: yarn install
      - if: steps.install.outputs.src == 'true'
        name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr
          path: pr/
